AppBundle\Entity\Invitation:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\InvitationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        senderName:
            type: string
            length: 255
        invitedName:
            type: string
            length: 255
        message:
            type: string
            length: 255
        status:
            type: string
            length: 255
    lifecycleCallbacks: {  }
